% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames*,x11names*}{xcolor}
%
\documentclass[
  12pt,
]{report}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
  \setmainfont[]{Arial}
  \setsansfont[]{Verdana}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Movies Recommendation in Flixster},
  pdfauthor={Robson Teixeira, Nuno Gomes},
  colorlinks=true,
  linkcolor=blue,
  filecolor=Maroon,
  citecolor=Blue,
  urlcolor=blue,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[top=25mm,bottom=25mm,left=25mm,right=25mm,heightrounded]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs}
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}

\title{Movies Recommendation in Flixster}
\author{Robson Teixeira, Nuno Gomes}
\date{17/05/2020}

\begin{document}
\maketitle

{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{2}
\tableofcontents
}
\hypertarget{introduction}{%
\subsection{1 Introduction}\label{introduction}}

\hypertarget{flixster-dataset}{%
\subsubsection{Flixster Dataset}\label{flixster-dataset}}

The \texttt{Flixster} is a social movie site which allow users to share
movie ratings, discover new movies and meet others with similar movie
taste. The dataset generated from \texttt{Flisxter} site consist of
8196077 ratings of 48794 movies by 147612 users. The data are
distributed in three files:

\begin{itemize}
\item
  \texttt{profile.txt} : contains informations regarding the users like
  user id, gender, age, location, for how long it has been a member
\item
  \texttt{movie-names.txt} : contains information regarding movies as
  name and movie id
\item
  \texttt{Ratings.time.txt} : contains information on the ratings given
  by users to movies and on which date
\end{itemize}

A summary of \emph{movies} is given below, togeher with several first
rows of dataframe:

\begin{verbatim}
## Rows: 66,730
## Columns: 2
## $ moviename <chr> "$ (Dollars) (The Heist)", "$5 a Day (Five Dollars a Day)...
## $ movieid   <int> 252, 253, 1, 254, 255, 256, 257, 2, 258, 3, 4, 5, 259, 26...
\end{verbatim}

\begin{verbatim}
##    variable q_zeros p_zeros q_na p_na q_inf p_inf      type unique
## 1 moviename       0       0    0    0     0     0 character  66730
## 2   movieid       0       0    0    0     0     0   integer  66730
\end{verbatim}

\begin{longtable}[]{@{}lr@{}}
\toprule
moviename & movieid\tabularnewline
\midrule
\endhead
\$ (Dollars) (The Heist) & 252\tabularnewline
\$5 a Day (Five Dollars a Day) & 253\tabularnewline
\$9.99 & 1\tabularnewline
\$windle (Swindle) & 254\tabularnewline
``BBC2 Playhouse'' Caught on a Train & 255\tabularnewline
``Independent Lens'' Race to Execution & 256\tabularnewline
\bottomrule
\end{longtable}

A summary of \emph{users} is given below, togeher with several first
rows of dataframe:

\begin{verbatim}
## Rows: 1,002,796
## Columns: 7
## $ userid      <int> 981904, 882359, 921220, 798641, 952904, 888, 300293, 80...
## $ gender      <chr> "Male", "Female", "Female", "Male", "Female", "Female",...
## $ location    <int> 111, 870, 993, 250, 172, 157, 221, 180, 233, 221, 282, ...
## $ memberfor   <chr> "2009-09-01 00:00:00", "2009-10-02 00:00:00", "2009-09-...
## $ lastlogin   <int> 1, 181, 124, 40, 44, 39, 91, 1, 26, 23, 490, 1097, 272,...
## $ profileview <chr> "19", "108", NA, "22", "21", "18", "13", NA, NA, "32", ...
## $ age         <chr> "19", "108", NA, "22", "21", "18", "13", NA, NA, "32", ...
\end{verbatim}

\begin{verbatim}
##      variable q_zeros p_zeros   q_na  p_na q_inf p_inf      type  unique
## 1      userid       0    0.00      0  0.00     0     0   integer 1002796
## 2      gender       0    0.00  67529  6.73     0     0 character       2
## 3    location   57726    5.76    203  0.02     0     0   integer    1429
## 4   memberfor       0    0.00    203  0.02     0     0 character      36
## 5   lastlogin   48949    4.88  57925  5.78     0     0   integer    3099
## 6 profileview       0    0.00 255564 25.49     0     0 character     126
## 7         age       0    0.00 255564 25.49     0     0 character     126
\end{verbatim}

\begin{longtable}[]{@{}rlrlrll@{}}
\toprule
userid & gender & location & memberfor & lastlogin & profileview &
age\tabularnewline
\midrule
\endhead
981904 & Male & 111 & 2009-09-01 00:00:00 & 1 & 19 & 19\tabularnewline
882359 & Female & 870 & 2009-10-02 00:00:00 & 181 & 108 &
108\tabularnewline
921220 & Female & 993 & 2009-09-01 00:00:00 & 124 & NA &
NA\tabularnewline
798641 & Male & 250 & 2009-11-01 00:00:00 & 40 & 22 & 22\tabularnewline
952904 & Female & 172 & 2009-11-01 00:00:00 & 44 & 21 &
21\tabularnewline
888 & Female & 157 & 2009-10-01 00:00:00 & 39 & 18 & 18\tabularnewline
\bottomrule
\end{longtable}

The variables \emph{gender} and \emph{age} are presented as character
and should be changed to factor and integer respectively.

The variables \emph{location}, \emph{memberfor}, \emph{lastlogin} and
\emph{profileview} are not needed for the context this analysis, so they
should be removed.

There are a significant number of \emph{NA's} in variables \emph{gender}
(67529 or around 6.73\% of total) and \emph{age} (255618 or around
25.49\% of total). We adopt the aproach the replacement the empty values
into a new value to treatmet of missing values. The empty values into
variable \emph{gender} will be replaced for new value \texttt{unknown}.
For the empty values into \emph{age} variable will be set the value
\texttt{0}.

A summary of \emph{ratings} is given below, togeher with several first
rows of dataframe:

\begin{verbatim}
## Rows: 8,196,077
## Columns: 4
## $ userid  <int> 882359, 882359, 882359, 882359, 882359, 882359, 882359, 882...
## $ movieid <int> 81, 926, 1349, 2270, 3065, 3522, 3583, 4216, 4871, 4917, 51...
## $ rating  <dbl> 1.5, 1.0, 2.0, 1.0, 5.0, 0.5, 0.5, 0.5, 3.5, 0.5, 1.0, 1.0,...
## $ date    <fct> 2007-10-10 00:00:00, 2007-10-10 00:00:00, 2007-10-10 00:00:...
\end{verbatim}

\begin{verbatim}
##   variable q_zeros p_zeros q_na p_na q_inf p_inf    type unique
## 1   userid       0       0    0    0     0     0 integer 147612
## 2  movieid       0       0    0    0     0     0 integer  48794
## 3   rating       0       0    0    0     0     0 numeric     10
## 4     date       0       0    0    0     0     0  factor   1450
\end{verbatim}

\begin{longtable}[]{@{}rrrl@{}}
\toprule
userid & movieid & rating & date\tabularnewline
\midrule
\endhead
882359 & 81 & 1.5 & 2007-10-10 00:00:00\tabularnewline
882359 & 926 & 1.0 & 2007-10-10 00:00:00\tabularnewline
882359 & 1349 & 2.0 & 2007-10-10 00:00:00\tabularnewline
882359 & 2270 & 1.0 & 2007-10-10 00:00:00\tabularnewline
882359 & 3065 & 5.0 & 2007-12-29 00:00:00\tabularnewline
882359 & 3522 & 0.5 & 2007-11-13 00:00:00\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{data-preparation}{%
\subsubsection{Data Preparation}\label{data-preparation}}

In this section we prepare the dataset to be used in the analysis. Some
steps of cleaning data are applied.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Remove no relevant variables}
\NormalTok{users <-}\StringTok{ }\KeywordTok{select}\NormalTok{(users, }\OperatorTok{-}\KeywordTok{c}\NormalTok{(location, memberfor, lastlogin, profileview) )}

\CommentTok{# Setting 'gender' as factors and 'age' as integer}
\NormalTok{users <-}\StringTok{ }\NormalTok{users }\OperatorTok{%>%}\StringTok{ }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{gender =} \KeywordTok{as.factor}\NormalTok{(gender)) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{age =} \KeywordTok{as.integer}\NormalTok{(age))}

\CommentTok{# Add column range_age into user data set}
\NormalTok{users <-}\StringTok{ }\NormalTok{users }\OperatorTok{%>%}\StringTok{ }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{range_age =} \KeywordTok{cut_width}\NormalTok{(age, }\DecValTok{10}\NormalTok{, }\DataTypeTok{boundary =} \DecValTok{0}\NormalTok{) )}

\CommentTok{# replace NA values into gender with "unknown"}
\NormalTok{users <-}\StringTok{ }\NormalTok{users }\OperatorTok{%>%}\StringTok{ }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{gender =} \KeywordTok{replace}\NormalTok{(gender, }\KeywordTok{is.na}\NormalTok{(gender), }\StringTok{"unknown"}\NormalTok{))}

\CommentTok{# replace NA values into age with "0"}
\NormalTok{users <-}\StringTok{ }\NormalTok{users }\OperatorTok{%>%}\StringTok{ }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{age =} \KeywordTok{replace}\NormalTok{(age, }\KeywordTok{is.na}\NormalTok{(age), }\DecValTok{0}\NormalTok{))}

\NormalTok{flixster <-}\StringTok{ }\NormalTok{ratings }\OperatorTok{%>%}\StringTok{ }\KeywordTok{left_join}\NormalTok{(users, }\DataTypeTok{by =} \StringTok{"userid"}\NormalTok{) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{left_join}\NormalTok{(movies, }\DataTypeTok{by =} \StringTok{"movieid"}\NormalTok{)}

\KeywordTok{remove}\NormalTok{(movies, users, ratings)}
\end{Highlighting}
\end{Shaded}

We split the dataset in two parts, the training set called
\texttt{train\_set} and the test set called \texttt{test\_set} with 70\%
and 30\% of the original dataset respectively.

\begin{verbatim}
## Joining, by = c("userid", "movieid", "rating", "date", "gender", "age", "range_age", "moviename")
\end{verbatim}

\end{document}
